#!/bin/bash

jetty_pid=`ps aux|grep java|grep jetty|grep -v grep|awk '{print $2}'`;

    if [ -n "$jetty_pid" ] 
    then
       kill $jetty_pid && echo "Jetty9 stopped successfully" || echo "Jetty9 stop failed"
    else 
	echo "Jetty9 already stopped";
    fi

